name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ghactionlint:
    name: GitHub Actions lint
    uses: ./.github/workflows/ghactionlint.yml
